# ==========================================================
# THIARAS OS
# CONFIGURACIÓN
# ==========================================================

NOMBRE_SISTEMA=THIARAS OS
VERSION=1.0.0

SMTP_SERVIDOR=smtp.gmail.com
SMTP_PUERTO=587

MINUTOS_ANTICIPACION=5

DB_URL=jdbc:postgresql://localhost:5432/thiaras_os
DB_USUARIO=postgres
